#!/bin/bash

SCRIPT_DIR=`dirname "$0"`

if [ ! -f Testing/TAG ]; then
	echo "No Testing/TAG file found, did ctest successfully run?" 1>&2
	exit 1
fi

latest_test=`head -n 1 < Testing/TAG`
results="Testing/$latest_test/Test.xml"
xsltproc ${SCRIPT_DIR}/ctest2junit.xsl "$results"